### ISSUE TITLE
Time format customization

### ISSUE THREAD

**Issue by irukard** [LMOspaceace/ajaxchat#12]
It would be nice if we could change time format - for example for 24h instead 12h AM/PM.

**Comment by Reaper88** [comment]
I've added a full time settings using of php date() function like the rest of the board so you can set it to your liking, ACP setting will override user settings also as both will be taken in account.

**Comment by irukard** [comment]
YAY!

**Comment by Reaper88** [comment]
Will be uploading changes soon.

**Comment by Reaper88** [comment]
Uploaded
