### ISSUE TITLE
The board logo does not displayed

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#20]
Hi,

on my board the board logo does not displayed when i'm on ./app.php/chat page.

EDIT: Maybe the problem its beceause i have activated the URL rewriting option in ACP (original option of phpBB 3.1).

On the http://domain.tld/chat URL it's ok the logo is displayed but the link in navbar it's http://domain.tld/app.php/chat why is that while i have activated URL rewriting ?

**Comment by Galixte** [comment]
Maybe the problem its beceause i have activated the URL rewriting option in ACP (original option of phpBB 3.1).

On the http://domain.tld/chat URL it's ok the logo is displayed but the link in navbar it's http://domain.tld/app.php/chat why is that while i have activated URL rewriting ?

**Comment by LMOspaceace** [comment]
in order to try to figure out your issue, i would need a link to your board and login to test. and i have url rewriting disabled on my board and all extensions that use app.php still show app.php. if your board is something that you do not want the public to see, you can always register on my site and pm me. you will need one post approved or post in chat who you are and your permissions will be set as soon as i can get to it.

**Comment by Galixte** [comment]
Website : www.ezcom-fr.com
Login : LMOspaceace
PWD : Test2015

**Comment by Galixte** [comment]
Hi,

OK your patches here fixes this issue:
https://github.com/LMOspaceace/ajaxchat/commit/2c97b7ec10dd701094713c9c2bfe115cdecc49fa
https://github.com/LMOspaceace/ajaxchat/commit/363bd7e7191f0e145c8293abc4c3390ad73ca0e6

But in Chat page and Index page (if the setting is activated) the two next links redirect on the bad link when i have the URL rewriting activated:
- Archive button
  - http://www.ezcom-fr.com/app.php/chat/archive instead of http://www.ezcom-fr.com/chat/archive
- Popup button
  - http://www.ezcom-fr.com/app.php/chat/popup instead of http://www.ezcom-fr.com/chat/popup

**Comment by LMOspaceace** [comment]
the templates have been fixed and now do not have app.php showing in the url. please let me know if it's fixed on your end

**Comment by Galixte** [comment]
It's OK for me thanks !-)
