### ISSUE TITLE
Gallery avatar paths are broken

### ISSUE THREAD

**Issue by dragosvr92** [LMOspaceace/ajaxchat#23]
If you use an avatar selected from a forum gallery... the shoued avatar path is broken...
It loads well after a page refresh though. This is the broken avatar path:

"./../images/avatars/gallery/Avatars/avatar06.jpg"
I guess its another bug in the engive, or your core fix doesnt apply on gallery avatars?

**Comment by Reaper88** [comment]
Core patch was only for uploaded avatars.
As for gallery avatar spaceace has checked them to be safe

**Comment by dragosvr92** [comment]
Ive checked with him about 15 hours ago and he could not figure out what is wrong with the gallery avatars.

**Comment by Reaper88** [comment]
ok i'll verify the core files

**Comment by Reaper88** [comment]
Yes, indeed core files are the same as the uploaded file so I'll send the fix to phpBB.

**Comment by dragosvr92** [comment]
Wow, that was fast. Did you figured it out? :)

Btw, i think it might be a good idea to include the fixed core files in the extension package.

**Comment by Reaper88** [comment]
as part of the extension it cannot be but i will post under spaceace's post in his forums about what to do until patch is done on phpBB core files

**Comment by Reaper88** [comment]
And yes I figured it out.

**Comment by Reaper88** [comment]
Patch pushed to phpBB already awaiting review

**Comment by Reaper88** [comment]
Patch merged to phpbb 3.1.x branch so it'll probly be in the next release

**Comment by dragosvr92** [comment]
Ive patched it the day you sent your ticket, from your gir profile. Saw the post on lmo too. Also the confirmation it was patched. lol :P

**Comment by Reaper88** [comment]
Cool does it work fine?

**Comment by dragosvr92** [comment]
yup. the gallery avatars worked after i applied the patch :)
Well done.

**Comment by Reaper88** [comment]
Alright cool, thanks.
