### ISSUE TITLE
subsilver2 style on top of page - Guests see chat center link

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#24]
Hi,

since your last commit about adding of subsilver2 style files, the guests see the link "Chat Center" on top of page but this page is not accessible of course. I think this link must not be displayed for guests like on prosilver style.

**Comment by LMOspaceace** [comment]
not really sure i understand. chat should have always been seen by guests. including the link in the header. you change this by setting the guest permissions to not view. on all my test sites, guests can go to the Chat Center page and see chat. you can see this on my main site http://www.livemembersonly.com/chat

**Comment by Galixte** [comment]
I don't set "See Chat" permission on "Yes" for guests, and on other style the "Chat center" link (in navbar) is not displayed for guests, why on subsilver2 ?

**Comment by Galixte** [comment]
Hi @LMOspaceace,

could you take a look ?

**Comment by Galixte** [comment]
Hi,

two screenshots for illustrate what i talk about: http://www.ezcom-fr.com/download/file.php?id=138 & http://www.ezcom-fr.com/download/file.php?id=139

**Comment by LMOspaceace** [comment]
i understand exactly what you mean. this will be fixed in the next release as all of the styles have to have the comments adjusted

**Comment by Galixte** [comment]
Thanks !-)
