### ISSUE TITLE
Respond to user BBCode error

### ISSUE THREAD

**Issue by dragosvr92** [LMOspaceace/ajaxchat#25]
Ive reported this to spaceace earlier but i said to put it here just in case. 

The respond to user bbcode insters this:
[color=#AA0000][b]@Dragosvr92 : [/color][/b]

It should be in this order:
[color=#AA0000][b]@Dragosvr92 :[/b] [/color]

**Comment by Reaper88** [comment]
Very true I'll check the javascript for that. Thanks.

**Comment by Reaper88** [comment]
What browser do you use?

**Comment by Reaper88** [comment]
Found the line and pushing to github now
