### ISSUE TITLE
CSS class change color and size on index page for the text of date and last visit

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#30]
Hi,

this code:

```
.time {
    font-size: 0.9em;
    color: #999999;
}
```

change the color and the size on index page for the text of actual date and last visit displayed under navbar.

**Comment by LMOspaceace** [comment]
fixed for the next release. thank you

**Comment by Galixte** [comment]
Hi,

When is the next release ?

**Comment by LMOspaceace** [comment]
the guy that is helping me has not been able to work on it lately as he has some things going on but as soon as the last 3 issues are worked out, it will be uploaded here. the last issues are hidden users showing in chat online list, posts needing approval should not show in chat, and the chat cookie delete function where the chat cookie is not getting deleted. i don't have anyone else to help and have to wait on him as i don't know how to fix those issues :(

**Comment by Galixte** [comment]
Ok, thanks for informations !

**Comment by Galixte** [comment]
Hi @Reaper88,

have you fixed this ?

**Comment by LMOspaceace** [comment]
i fixed this issue in the stylesheets

**Comment by Galixte** [comment]
thanks !
