### ISSUE TITLE
Uninstall extension with delete data does not delete users table informations

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#31]
Hi,

when i uninstall this extension and i delete data, the process does not delete the fields added in users table of phpBB.

**Comment by LMOspaceace** [comment]
i will make sure this gets fixed. thanks :)

**Comment by Reaper88** [comment]
has been fixed will be released with next release.

**Comment by Galixte** [comment]
thanks Reaper88 !
