### ISSUE TITLE
Others officials styles

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#37]
Hi @LMOspaceace,

could you test your extension on others officials styles from phpBB.com:
- We_universal style | https://www.phpbb.com/customise/db/style/we_universal/ | displaying of buttons are all on left side ;
- PBTech | https://www.phpbb.com/customise/db/style/pbtech/ | The buttons used a particular font, so buttons should have a padding-bottom more important ;
- PBWoW 3 | https://www.phpbb.com/customise/db/style/pbwow3/ | The buttons used a particular font, so buttons should have a padding-bottom more important.

**Comment by LMOspaceace** [comment]
PB line of styles are fixed in this version now.

still working on we_universal

**Comment by LMOspaceace** [comment]
i think i have we_universal fixed in the prosilver inherited stylesheet. can you confirm this with the updated files?

**Comment by Galixte** [comment]
Yes i will. ;)

**Comment by Galixte** [comment]
Hi @LMOspaceace,

I have tested on We universal and it apprears seem to be OK.

Juste one thing, the title “Chat Center” is not displayed on left side, it’s placed near the middle, like center but just one bit on left, it should be placed completly on left side like prosilver style.

For PBTech and PBWow 3 styles, it would be better if there are a little space under buttons, please.

**Comment by LMOspaceace** [comment]
styling on we_universal is done. the "Chat Center" text is aligned in the center due to the category names for the forums in that style are aligned in the center of their element.

i see the same spacing on the PB line as i do in prosilver under the buttons. are you wanting more spacing?

**Comment by Galixte** [comment]
After tests with your last snapshot, for We universal style, all languages have a missing spacing below buttons, see that: http://www.ezcom-fr.com/download/file.php?id=313.

And for PBtech et PBWoW 3 styles, the problem is only for French language with “Chat font colour” button which have a missing spacing above, see that: http://www.ezcom-fr.com/download/file.php?id=312.

**Comment by Galixte** [comment]
Hi,

there is a bug in this extension with We_universal style, see that: http://www.ezcom-fr.com/download/file.php?id=316&mode=view. This issue concerns new message by all users, by me and by others.

**Comment by LMOspaceace** [comment]
the issue with we_universal putting messages in the chat header was just an element id issues and is now fixed. i also added a 3px margin on the bottom of the buttons that should fix any spacing issues. let me know if these are fixed :)

**Comment by Galixte** [comment]
Thanks for all, it’s ok for me.
