### ISSUE TITLE
Add ABBC3 buttons

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#39]
Hi,

for a future release, could you add the ABBC3 buttons from this extension: https://github.com/VSEphpbb/abbc3.

Because when this extension is activated, the buttons of BBCodes are don’t display 
as they should.

**Comment by LMOspaceace** [comment]
i don't believe that any extension should include files from other extensions unless they hinder the function of the extension. i installed the abbc3 extension to test and the bbcode buttons looked like normal bbcode buttons to me and they worked fine. but then, of course, i had to manually delete all the bbcodes that extension installed because vse seems to think it's ok if an extension leaves a large portion of itself behind after deleting the extension data to uninstall it. if people install that extension and want those images added, they can add them as they need them. sorry

**Comment by Galixte** [comment]
Hi @LMOspaceace,

on my board, on viewtopic a registered user sees this: http://www.ezcom-fr.com/download/file.php?id=321.
And on Ajax Chat this user sees this: http://www.ezcom-fr.com/download/file.php?id=320.

I have some custom BBCodes which a registered user can’t use, because some BBCode have permissions, in normal way the user shouldn’t see them, like on viewtopic or posting pages.

You say: “if people install that extension and want those images added, they can add them as they need them”, but how to add image button from ABBC3 extension in chat ajax, because now the bbcodes buttons are displayed like phpBB should display them.

**Comment by LMOspaceace** [comment]
i see your point. now, actually looking at where the images are stored in that extension, they are in \vse\abbc3\images\icons and not even part of any style folders so you would probably have to ask VSE how to even add them as i don't know what conditional comment would be needed.

**Comment by Galixte** [comment]
Hi @LMOspaceace,

have you seen the VSE answers ? https://github.com/VSEphpbb/abbc3/issues/18

**Comment by Reaper88** [comment]
I'll see what's up with that soon galixte.

**Comment by LMOspaceace** [comment]
already fixing it lol

will be updating Git shortly with the changes

**Comment by Galixte** [comment]
thanks guys !

**Comment by LMOspaceace** [comment]
got the abbc3 bbcodes showing correctly but have issues with font size and selecting a different font. but here's how it looks

http://www.livemembersonly.com/images/ui/abbc3.png

as soon as those 2 problems are fixed, i will be updating the files here

**Comment by Galixte** [comment]
Nice good job, many thanks to you. ;)

**Comment by iMattPro** [comment]
> i had to manually delete all the bbcodes that extension installed because vse seems to think it's ok if an extension leaves a large portion of itself behind after deleting the extension data to uninstall it.

Just to clarify, ABBC3.1 adds mostly stand-alone custom bbcodes. If deleting ABBC3.1 removed them too, then every post using them would be broken. So it's a courtesy to any user who wants to stop using ABBC3.1 now or in the future to be able to do so without having to worry about all their old posts breaking as a result.
https://www.phpbb.com/customise/db/extension/advanced_bbcode_box/faq/1526

**Comment by LMOspaceace** [comment]
but for those that only want to test your extension or make things compatible with it, it leaves behind a mess of bbcodes that you have to manually delete. normally when an extension leaves parts of itself behind after it's data is deleted, that is very much undesired by most people

**Comment by iMattPro** [comment]
Most of those bbcodes are not "parts of itself". They are goodies. It would be far more undesirable to "break" the board upon removing an extension.

**Comment by LMOspaceace** [comment]
i still think when the data gets deleted for an extension that it should remove everything it added to the board. otherwise deleting the data for it is useless and not up to what should be phpBB standards
