### ISSUE TITLE
Notification about new post/update is not displayed

### ISSUE THREAD

**Issue by sq6jny** [LMOspaceace/ajaxchat#40]
Hello,
thanks for great extension, I'm using it for a long time. Few days ago I have updated to the last version, but when I'm creating a new post in the forum I have got only a blank line with my nick in the chat. In the previous version it worked correctly.
Could you check this, please? I can create a test account and provide an access to my sandbox if you wish.

Thank you and best regards,
Marcin

**Comment by LMOspaceace** [comment]
i will look into this on Monday as i will be away all weekend. sorry for any issues this has caused

**Comment by Galixte** [comment]
Hi,

with the last snapshot and on phpBB 3.1.5, i don’t have this bug.

**Comment by sq6jny** [comment]
Hello,
I forgot to mention, in target system I'm using phpBB 3.1.5 and AjaxChat 3.0.1-BETA, cache was purged, extension data removed, etc. The only modifications I have made were:
- change of the height of chat box to 450 in ajaxchat\styles\prosilver\theme\ajax_chat.css
- change in the first line of ajaxchat\styles\prosilver\template\chat_body.html from 
   
  to
  
  The second change prevents from showing chat to guests (I have set all Guests permission to 'none' but maybe I missed something, without this correction I have got only a message 'You have to be logged in to write in chat' or sth. but the box with conversation is visible)

Thank you and best regards,
Marcin

**Comment by LMOspaceace** [comment]
i also cannot reproduce this issue with a fresh phpBB 3.1.5 install and said modifications.

however, i did remove a small post visibility function in the listener. updating the listener file and purging the cache is all that is needed to update to the new file. see if that helps as it did fix the post edited notification message in chat

**Comment by sq6jny** [comment]
Hello,

I installed an updated package, but still with no result. But I checked the language file (I'm using PL) and there were missing lines:
                        'CHAT_NEW_POST'         => 'nowa odpowiedź: <a href="%1$s">%2$s</a>',
            'CHAT_NEW_TOPIC'        => 'nowy temat: <a href="%1$s">%2$s</a>',
            'CHAT_POST_EDIT'        => 'edytowano: <a href="%1$s">%2$s</a>',
            'DELETE_CHAT_COOKIE'    => 'Usuń cookie',
So after adding these lines (already translated, they can be added to the package) the problem has been solved.

Thank you for your time and best regards,
Marcin

**Comment by LMOspaceace** [comment]
glad you found the issue. if possible, could you create a pull request with the missing language entries for the pl language as i only use en lol

**Comment by sq6jny** [comment]
Hello,
I have just created a new pull request.

Thank you and best regards

2015-06-28 21:06 GMT+02:00 Darin Wilton notifications@github.com:

> glad you found the issue. if possible, could you create a pull request
> with the missing language entries for the pl language as i only use en lol
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LMOspaceace/ajaxchat/issues/40#issuecomment-116315555
> .

## 

Marcin Sroczyk
SQ6JNY
