### ISSUE TITLE
Chat font colour

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#46]
The displaying is not correct.

**Comment by LMOspaceace** [comment]
i don't understand what you mean. what is not displaying correctly?

**Comment by Galixte** [comment]
Hi,

see that: http://www.ezcom-fr.com/download/file.php?id=332

**Comment by LMOspaceace** [comment]
the only way i can reproduce this issue is by removing the file root/images/spacer.gif 

this file is in the images folder in the default phpBB package and should be present in all phpBB 3.1.x installations

**Comment by Galixte** [comment]
Thanks my update to phpBB 3.1.5 has missed this file.
