### ISSUE TITLE
Mofule title

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#53]
Hi @LMOspaceace @Reaper88,

the module title should be: https://github.com/LMOspaceace/ajaxchat/blob/master/acp/ajaxchat_info.php#L21, `ACP_AJAX_CHAT` instead of `ADMIN_AJAXCHAT`, no ?

**Comment by LMOspaceace** [comment]
correct and nice find. it will be corrected in the next release with the other issues

**Comment by LMOspaceace** [comment]
title name fixed

**Comment by Galixte** [comment]
thank you ;)
