### ISSUE TITLE
php parse error

### ISSUE THREAD

**Issue by rezmoth** [LMOspaceace/ajaxchat#54]
I'm using phpbb 3.1.6, php 5.3
When I try to enable the extension from phpbb extension manager it throws an error: "Parse error: syntax error, unexpected '[' in ../forum/ext/spaceace/ajaxchat/migrations/acp_settings.php on line 18"

**Comment by LMOspaceace** [comment]
this is not an issue with the extension. this is your host not meeting the minimum requirement of PHP 5.4. PHP 5.3 has long been obsolete and not supported and no hosting platform should be using it anymore. in fact, PHP 5.4 has recently reached the end of it's life as well.

**Comment by lanevegame** [comment]
Hello, I'm having the same issue but my host is using php 5.6. Is there any workaround?

**Comment by LMOspaceace** [comment]
this should not happen on php 5.4 and up as the brackets [ and ] were 
introduced in 5.4. look in your ACP phpinfo to make sure your board is 
running php greater than 5.3
