### ISSUE TITLE
Function EDIT problem

### ISSUE THREAD

**Issue by Jiipey-K** [LMOspaceace/ajaxchat#62]
Hello, i'm french user.

I have a problem when i edit the message with the function Edit, the letter "é" get "?".

Exemple : "Bien joué" get "Bien jou?". :?

Thank you.

**Comment by LMOspaceace** [comment]
this will be fixed in the next release that is coming by this weekend

**Comment by Jiipey-K** [comment]
Thank you. The best chatbox for me :D 

Perfect work.

**Comment by LMOspaceace** [comment]
it has been fixed in 3.0.17
