### ISSUE TITLE
Error: /phpbb/user.php on line 453: sprintf(): Too few arguments

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#63]
Hi @LMOspaceace,

See this post: https://www.phpbb.com/community/viewtopic.php?p=14486366#p14486366

**Comment by Galixte** [comment]
Hi @LMOspaceace,

i have updated my second message here: https://www.phpbb.com/community/viewtopic.php?p=14486711#p14486711

Could you take a look, please ?

**Comment by LMOspaceace** [comment]
found the issue and fixed it
