### ISSUE TITLE
Missing templates

### ISSUE THREAD

**Issue by Galixte** [LMOspaceace/ajaxchat#65]
Hi @LMOspaceace,

why you have completly destroy a lot of templates since this commit: https://github.com/LMOspaceace/ajaxchat/commit/9ce13a0d3c0b2c90201839b5fae7afd98f1198d4

Before the 6 june, there were all those styles: https://github.com/LMOspaceace/ajaxchat/tree/5f3d426f4cdd0f59c683607368d48664ccf3f712/styles

It’s for the pleasure of phpBB.com ? :P

**Comment by LMOspaceace** [comment]
the extensions team wanted the templates split up. the actual purpose for having to do it that way, i have no idea. but, in the process, i made a lot of changes to the templates and chat works with many styles now without having to include a set of templates for each one
