### ISSUE TITLE
PHP 7.1.1 chat quote error...

### ISSUE THREAD

**Issue by LMOspaceace** [LMOspaceace/ajaxchat#68]
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 779: A non-numeric value encountered
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 780: A non-numeric value encountered
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 781: A non-numeric value encountered

looks like i have to fix this

**Comment by Reaper88** [comment]
If too much trouble let me know.

**Comment by LMOspaceace** [comment]
Reaper88 found the code that was not needed so this is fixed
