### ISSUE TITLE
board in folder displays improper member link

### ISSUE THREAD

**Issue by LMOspaceace** [LMOspaceace/ajaxchat#69]
for the board installed in subfolder (like domain.ex/forum). Once you load the chat page, member profiles links in the chat window are ok. After Ajax got its work (say, the message sent etc), profile links (in the chat) lose the folder path and look like domain.ex/memberlist.php?mode=viewprofile&u=2. After hard reloading the page, they're ok again until the page got Ajaxed again, and so on.

issue reported by rxu from phpbb.com

**Comment by Reaper88** [comment]
Fixed With Pull Request #70

**Comment by LMOspaceace** [comment]
thank you
