### ISSUE TITLE
Not work after 3.2.1 update...

### ISSUE THREAD

**Issue by The-Asylum** [LMOspaceace/ajaxchat#74]
Hello,

I have use this ext. with the 3.2 with no problem, but now after the 3.2.1 update, the chat dont appear on any place in my forum, but i can see it in my admin pannel, can you help me?

Thanks

**Comment by Galixte** [comment]
@LMOspaceace, could you take a look, please?

**Comment by The-Asylum** [comment]
Sorry, i just dont have manage the permissions, its ok now ;-)

**Comment by Galixte** [comment]
Close the ticket, please. ;)

**Comment by LMOspaceace** [comment]
closed
