### ISSUE TITLE
{hit} malware hit {CAV}Sanesecurity.Malware.26399.JsHeur found for .../ajax_chat.js

### ISSUE THREAD

**Issue by lol-deb** [LMOspaceace/ajaxchat#75]
Hi,

My Maldet scanner (Debian) detect the file ajax_chat.js as being infected by Malware.26399.JsHeur:
`{hit} malware hit {CAV}Sanesecurity.Malware.26399.JsHeur found for /path/to/ajax_chat.js`

http://sane.mxuptime.com/s.aspx?id=Sanesecurity.Malware.26399.JsHeur

It is probably a false positive, but as the ajax_chat.js file is quarantined the plugin is no longer usable ...

Can you check and modify the js so that it is "clean"?

**Comment by LMOspaceace** [comment]
i can assure you that it is a false positive and this is the first time i've ever heard of this. i honestly have no idea how to modify it to make it clear a scanner

**Comment by lol-deb** [comment]
Ok thank you for the quick return.
I putted the .js in the whitelist of maldetect

You can mailto sanesecurity for false positive detection:
http://sanesecurity.com/support/false-positives/

I'll close this ticket.

Thanks,
Rgds.
